##
## Example Docker Compose file
##
## This example shows how to expose the K-Link on localhost
## For more information please check ./docs/installation.md
##
## Lines that starts with "##" are comments, lines that starts
## with "#" are optional or advanced configurations, that can be
## uncommented if needed
##

version: '2'

networks:
  internal:

services:
  ## Database for the K-Registry
  registry-db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: "kregistry"
      MYSQL_USER: "kregistry"
      MYSQL_ROOT_PASSWORD: "238..."
      MYSQL_PASSWORD: "b25..."
    networks:
      - internal
    volumes:
      - "./storage/database:/var/lib/mysql"

  ## the K-Link Registry
  registry:
    image: "klinktech/k-link-registry:0.2.0"
    environment:
      REGISTRY_DB_HOST: "registry-db"
      REGISTRY_DB_NAME: "kregistry"
      REGISTRY_DB_USER: "kregistry"
      REGISTRY_DB_PASS: "kregistry"
      REGISTRY_HTTP_DOMAIN: "klink.example.example"
      REGISTRY_HTTP_BASE_PATH: "/registry"
      ## Default administrator
      REGISTRY_ADMIN_USERNAME: "admin@registry.local"
      REGISTRY_ADMIN_PASSWORD: "****"
      ## Mail service configuration, values are for example only, change them according to your mail server
      # REGISTRY_SMTP_HOST: "smtp.registry.local"
      # REGISTRY_SMTP_PASS: "****"
      # REGISTRY_SMTP_FROM: "K-Link <fake@klink.example.example>"
      # REGISTRY_SMTP_PORT: "587"
    depends_on:
      - database
    networks:
      - internal

  ## The Search Engine service
  engine:
    image: "klinktech/k-search-engine:1.0.1-1"
    volumes:
      - "./storage/index:/opt/solr/k-search/k-search/data"
    environment:
      KLINK_SOLR_MYHOST: engine # this is the external address of solr
    networks:
      - internal

  ## The Search Engine API
  ksearch:
    image: "klinktech/k-search:3.6.0-2"
    expose:
      - "80"
    environment:
      ## Application settings
      - APP_ENV=prod # Use the production environment, use "dev" for development
      - APP_DEBUG=0 # Enable the debug feature
      ## Solr search configuration
      - SOLR_HOST=engine # this is the external address of Solr
      - SOLR_CORE=k-search # this is the Solr index name
      ## Registry configuration
      - KLINK_REGISTRY_ENABLED=1
      - KLINK_REGISTRY_API_URL=http://registry/
    volumes:
      - "./storage/data:/var/www/k-search/var/data-downloads"
    depends_on:
      - engine
      - registry
    networks:
      - internal

  klink:
    image: "klinktech/k-link:0.1.0"
    ports:
      - 8181:80
    depends_on:
      - ksearch
    networks:
      - internal
